//! The colours a chart **encodes with** — as distinct from the ones chrome is
//! painted in.
//!
//! # Why this is a separate axis from [`crate::theme::ColorTokens`]
//!
//! The two answer different questions, and collapsing them silently produces
//! wrong charts. A semantic token says *what a thing means* — this failed, this
//! is a warning. An encoding colour says *where this datum sits*, and its job is
//! to preserve a relationship: distinguishable-from, more-than, further-from-
//! zero. Mapping a six-way categorical ramp onto four semantic tokens makes two
//! categories collide, and a stacked chart with two identical bands is not a
//! styling regression — it is a wrong chart that still looks fine to whoever
//! shipped it.
//!
//! # Kinds, because the kind is what carries the invariant
//!
//! There is no single "chart palette". There are five kinds in this suite, each
//! with a different thing a theme must not break:
//!
//! | Kind | Used by | Invariant |
//! |---|---|---|
//! | [`SeriesPalette::categorical`] | `channel_bands`, ring classes | adjacent pairs separable under dichromacy |
//! | [`Diverging`] | flow in/out, price up/down, over/under | arms separable **and** a neutral at surface luminance |
//! | [`Sequential`] | rarity rank, density, depth | **monotonic in luminance** |
//! | [`IdentityEnvelope`] | `utxo_map` policy colours | unbounded hues, bounded legibility |
//! | *fixed / physical* | `asset_card` foil, terrain metaphor | **not themed at all** |
//!
//! That last row is a real category, not an oversight. The holographic foil is a
//! hue rotation simulating a physical effect; a themed rainbow is not a rainbow.
//! Those literals stay literal, and the reason is written where they live.
//!
//! # The enforcement is the deliverable
//!
//! Letting a theme supply chart colours is only safe because each invariant is a
//! test over `Theme::PRESETS` (`tests/series_palette.rs`). That is not
//! belt-and-braces: within an hour of the categorical validator existing it
//! caught a sixth slot colliding at ΔE 7.3 under protanopia, and the ordinal
//! ramp below was found non-monotonic after years in the tree. Without the
//! tests, every new preset is a chance to ship an encoding that reads fine to
//! the person who added it and lies to everyone else.
//!
//! # Colour should not be the only channel
//!
//! Where position, size or shape already carry the encoding, theming colour is
//! low-risk — `flow_ring` deforms the radius, the token view makes depth the
//! headline on a log scale. Where colour is the only channel, the invariant test
//! is the only thing between a theme and an unreadable chart.

use egui::Color32;

// ============================================================================
// Perceptual space
// ============================================================================
//
// Oklab, because ramps generated by lerping sRGB channels are neither
// perceptually even nor reliably monotonic — they bow through muddy midpoints
// and can non-monotonically dip in lightness, which is exactly the failure the
// `Sequential` kind exists to prevent.

/// sRGB (0–255) to linear.
fn to_linear(v: u8) -> f32 {
    let v = v as f32 / 255.0;
    if v <= 0.04045 {
        v / 12.92
    } else {
        ((v + 0.055) / 1.055).powf(2.4)
    }
}

/// Linear to sRGB (0–255).
fn to_srgb(v: f32) -> u8 {
    let v = v.clamp(0.0, 1.0);
    let s = if v <= 0.003_130_8 {
        12.92 * v
    } else {
        1.055 * v.powf(1.0 / 2.4) - 0.055
    };
    (s * 255.0).round() as u8
}

/// sRGB to Oklab `[L, a, b]`.
fn oklab(c: Color32) -> [f32; 3] {
    let (r, g, b) = (to_linear(c.r()), to_linear(c.g()), to_linear(c.b()));
    let l = (0.412_221_46 * r + 0.536_332_54 * g + 0.051_445_995 * b).cbrt();
    let m = (0.211_903_5 * r + 0.680_699_5 * g + 0.107_396_96 * b).cbrt();
    let s = (0.088_302_46 * r + 0.281_718_84 * g + 0.629_978_5 * b).cbrt();
    [
        0.210_454_26 * l + 0.793_617_8 * m - 0.004_072_047 * s,
        1.977_998_5 * l - 2.428_592_2 * m + 0.450_593_7 * s,
        0.025_904_037 * l + 0.782_771_77 * m - 0.808_675_77 * s,
    ]
}

/// Oklab `[L, a, b]` back to sRGB.
fn from_oklab(lab: [f32; 3]) -> Color32 {
    let [ll, aa, bb] = lab;
    let l = (ll + 0.396_337_78 * aa + 0.215_803_76 * bb).powi(3);
    let m = (ll - 0.105_561_346 * aa - 0.063_854_17 * bb).powi(3);
    let s = (ll - 0.089_484_18 * aa - 1.291_485_5 * bb).powi(3);
    Color32::from_rgb(
        to_srgb(4.076_741_7 * l - 3.307_711_6 * m + 0.230_969_94 * s),
        to_srgb(-1.268_438 * l + 2.609_757_4 * m - 0.341_319_38 * s),
        to_srgb(-0.004_196_086 * l - 0.703_418_6 * m + 1.707_614_7 * s),
    )
}

/// Interpolate between two colours in Oklab. `t` is clamped to `0..=1`.
fn mix(a: Color32, b: Color32, t: f32) -> Color32 {
    let t = t.clamp(0.0, 1.0);
    let (x, y) = (oklab(a), oklab(b));
    from_oklab([
        x[0] + (y[0] - x[0]) * t,
        x[1] + (y[1] - x[1]) * t,
        x[2] + (y[2] - x[2]) * t,
    ])
}

// ============================================================================
// Sequential
// ============================================================================

/// An **ordinal** ramp: rank, depth, density, recency — anything where the
/// reader's question is "more or less?".
///
/// # Generated, not enumerated, and that is the whole point
///
/// The theme supplies two endpoints and the ramp is interpolated in Oklab. The
/// alternative — listing fixed steps — is what the suite had, and it produced
/// this, from `rarity_rank_color` (WCAG relative luminance):
///
/// ```text
/// top 1%   0.628
/// top 5%   0.475   <- DARKER than the tier below it
/// top 10%  0.562
/// top 25%  0.525
/// rest     0.120
/// ```
///
/// Gold, amber, cyan, green, grey: five hand-picked hues, each defensible alone,
/// non-monotonic as a ramp. A reader scanning by brightness reads the rank order
/// wrong, and in greyscale or under either common dichromacy the ramp is
/// actively misleading rather than merely ugly. Nobody noticed for years,
/// because nothing could notice.
///
/// Generating from endpoints makes monotonicity **structural**: `at()` is linear
/// in Oklab L between a dim end and a bright one, so it cannot dip. Enumeration
/// would buy art-direction control at the cost of re-earning that by hand, per
/// theme, forever.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Sequential {
    /// The "least" end. Should recede toward the surface.
    pub low: Color32,
    /// The "most" end.
    pub high: Color32,
}

impl Sequential {
    /// A ramp **around one hue** — dark to light, keeping `base`'s colour.
    ///
    /// For "ordered slices of one quantity": a top-1% / top-10% / rest
    /// breakdown, a two-band supply bar. `holder_formation` says why this is not
    /// the categorical ramp — "these bands are ordered slices of one quantity,
    /// and a categorical set would imply they are unrelated things". Sharing a
    /// hue is the part that says *related*; the lightness is what says *more*.
    ///
    /// Built in Oklab so the endpoints keep `base`'s hue and chroma and differ
    /// only in lightness, which is what makes the ramp monotonic.
    pub fn around(base: Color32) -> Self {
        let [_, a, b] = oklab(base);
        Self {
            low: from_oklab([0.38, a, b]),
            high: from_oklab([0.82, a, b]),
        }
    }

    /// The colour at `t` in `0..=1`, where 0 is [`Self::low`].
    pub fn at(&self, t: f32) -> Color32 {
        mix(self.low, self.high, t)
    }

    /// `n` evenly spaced steps, low to high. `n == 1` yields the high end —
    /// a single-step ramp is showing the reader "the most", not "the least".
    pub fn steps(&self, n: usize) -> Vec<Color32> {
        match n {
            0 => Vec::new(),
            1 => vec![self.high],
            _ => (0..n).map(|i| self.at(i as f32 / (n - 1) as f32)).collect(),
        }
    }

    /// The step for `rank` out of `total`, **inverted** so rank 1 is the
    /// brightest. Ranks are ordinal-from-the-top; density and depth are not, and
    /// use [`Self::at`] directly.
    pub fn by_rank(&self, rank: u32, total: u32) -> Color32 {
        if total == 0 {
            return self.low;
        }
        let pct = (rank as f32 / total as f32).clamp(0.0, 1.0);
        self.at(1.0 - pct)
    }
}

// ============================================================================
// Diverging
// ============================================================================

/// A **bipolar** encoding: value arriving vs leaving, price up vs down, over vs
/// under target.
///
/// The neutral is not decoration. A diverging scale's midpoint is "no
/// difference", and if it renders as a colour rather than as the surface, every
/// chart using the scale gains a band of visual weight exactly where the data
/// says nothing is happening.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Diverging {
    /// The "toward us / up / over" arm.
    pub positive: Color32,
    /// The "away / down / under" arm.
    pub negative: Color32,
    /// The midpoint. Should sit near the surface, not between the two hues.
    pub neutral: Color32,
}

impl Diverging {
    /// The colour at `t` in `-1.0..=1.0`, where 0 is [`Self::neutral`].
    pub fn at(&self, t: f32) -> Color32 {
        let t = t.clamp(-1.0, 1.0);
        if t >= 0.0 {
            mix(self.neutral, self.positive, t)
        } else {
            mix(self.neutral, self.negative, -t)
        }
    }
}

// ============================================================================
// Identity
// ============================================================================

/// The envelope for **hashed identity** colours — one colour per policy, per
/// wallet, per anything with unbounded cardinality.
///
/// A ramp cannot serve this: there is no Nth colour when N is "every policy on
/// chain". What a theme *can* own is the envelope — how saturated and how light
/// those hues are allowed to be — which is what keeps 648 arbitrary hues legible
/// on this particular surface without constraining which hue any one identity
/// gets. Hue is the hash's to choose; legibility is the theme's.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct IdentityEnvelope {
    /// Chroma in Oklab terms, as a 0..1 fraction of a vivid reference.
    pub saturation: f32,
    /// Oklab lightness, 0..1. The band that has to clear the surface.
    pub lightness: f32,
}

impl IdentityEnvelope {
    /// A stable colour for `hash`. Same hash, same colour, for the life of the
    /// theme — identity colours are compared across screenshots and sessions.
    pub fn color(&self, hash: u64) -> Color32 {
        // 72 hue steps, matching the resolution `utxo_map` already used.
        let hue = (hash % 72) as f32 * (std::f32::consts::TAU / 72.0);
        // 0.16 is roughly the chroma of a vivid sRGB hue in Oklab; scaling it
        // keeps the whole wheel inside gamut at this lightness.
        let chroma = 0.16 * self.saturation.clamp(0.0, 1.0);
        from_oklab([
            self.lightness.clamp(0.0, 1.0),
            chroma * hue.cos(),
            chroma * hue.sin(),
        ])
    }
}

// ============================================================================
// The palette
// ============================================================================

/// Every encoding a chart in this suite draws from.
///
/// # This vocabulary was already shared, it just wasn't named
///
/// `0x3987e5` ("value arriving") was written out as a literal in **thirteen**
/// modules and `0xe08a2e` ("value leaving") in seven — `flow_ring`,
/// `time_spine`, `flow_matrix`, `custody_walk`, `holder_field`,
/// `activity_lanes`, `party_annotator` and the rest. One vocabulary, maintained
/// by copy-paste, that no theme could move and no one could revise. Naming it
/// here is what makes both possible.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SeriesPalette {
    /// The categorical ramp, in assignment order. Distinguishable by hue;
    /// **never index this for a meaning** — that is what `ColorTokens` is for.
    ///
    /// **Five, and do not extend it.** Five is how many hues survive the
    /// adjacent-pair separation floors under both common dichromacies on a dark
    /// surface. The first draft of this struct carried six and the validator
    /// rejected it immediately — the sixth collapsed onto the first at ΔE 7.3
    /// under protanopia. A sixth series folds into [`Self::other`].
    pub categorical: [Color32; 5],
    /// The folded "everything else" band. Deliberately outside the categorical
    /// order so it never reads as one more series.
    pub other: Color32,
    /// **Nothing has been looked at yet** — deliberately distinct from a
    /// measured zero. Rendering "unknown" and "none" the same way is how a
    /// half-finished walk reads as a finished one.
    pub unobserved: Color32,
    /// Value arriving vs leaving — the direction encoding thirteen modules
    /// share.
    pub flow: Diverging,
    /// A short **ordinal classification**: how close a party is to the subject
    /// (`flow_ring`'s core / associate / customer). Innermost first; the fourth
    /// step is [`Self::unobserved`], because "nobody has looked" is the absence
    /// of a judgement rather than a fourth class.
    ///
    /// # Why this is enumerated when [`Sequential`] is generated
    ///
    /// Because its stops carry an **external** constraint, and no two-endpoint
    /// interpolation can be steered to meet one. These dots are drawn over
    /// chords painted in [`Self::flow`], and a seat must never be mistakable for
    /// a payment — violet, the obvious first pick, collapses onto the chord blue
    /// under protanopia at ΔE 5.1. A single-hue lightness ramp (which is what
    /// `Sequential` would give) was tried and failed differently: associate and
    /// customer measured ΔE 22 normal / 19 deutan, clearing the floor and still
    /// reading as one colour on 4px dots. The ramp moves in hue as well —
    /// pale aqua → green → deep teal — taking that pair to ΔE 53 / 44.
    ///
    /// So: generated where the only requirement is monotonicity, enumerated
    /// where the stops must also dodge colours outside the ramp. Both are
    /// checked; see `tests/series_palette.rs`.
    pub classes: [Color32; 3],
    /// Rank, depth, density: anything ordinal.
    pub ordinal: Sequential,
    /// The envelope for hashed identity colours.
    pub identity: IdentityEnvelope,
}

impl SeriesPalette {
    /// The values the suite already used, in their observed proportions.
    pub const fn tokyo_night() -> Self {
        Self {
            categorical: [
                Color32::from_rgb(0x39, 0x87, 0xe5),
                Color32::from_rgb(0xd9, 0x59, 0x26),
                Color32::from_rgb(0x19, 0x9e, 0x70),
                Color32::from_rgb(0xc9, 0x85, 0x00),
                Color32::from_rgb(0xd5, 0x51, 0x81),
            ],
            other: Color32::from_rgb(0x6b, 0x6b, 0x80),
            unobserved: Color32::from_rgb(0x4d, 0x54, 0x78),
            flow: Diverging {
                positive: Color32::from_rgb(0x39, 0x87, 0xe5),
                negative: Color32::from_rgb(0xe0, 0x8a, 0x2e),
                neutral: Color32::from_rgb(0x2a, 0x2e, 0x3f),
            },
            classes: [
                Color32::from_rgb(0xa5, 0xf3, 0xe4), // core — the subject itself
                Color32::from_rgb(0x3d, 0xdc, 0x84), // paid BY it
                Color32::from_rgb(0x0f, 0x8f, 0x8a), // bought FROM it
            ],
            ordinal: Sequential {
                low: Color32::from_rgb(0x3b, 0x40, 0x5a),
                high: Color32::from_rgb(0xff, 0xd7, 0x00),
            },
            identity: IdentityEnvelope {
                saturation: 0.75,
                lightness: 0.72,
            },
        }
    }

    /// Brighter and cooler, to sit on the marketplace palette's near-black.
    pub const fn opensea() -> Self {
        Self {
            categorical: [
                Color32::from_rgb(59, 142, 240),
                Color32::from_rgb(251, 146, 60),
                Color32::from_rgb(52, 199, 123),
                Color32::from_rgb(245, 181, 68),
                Color32::from_rgb(244, 88, 110),
            ],
            other: Color32::from_rgb(107, 107, 128),
            unobserved: Color32::from_rgb(71, 78, 92),
            flow: Diverging {
                positive: Color32::from_rgb(59, 142, 240),
                negative: Color32::from_rgb(251, 146, 60),
                neutral: Color32::from_rgb(34, 37, 44),
            },
            // Same aqua → green → teal band, brightened to this palette. The
            // band is not a style choice: it is the region that stays clear of
            // both chord colours under dichromacy, and the validator holds this
            // preset to it exactly as it holds the default.
            classes: [
                Color32::from_rgb(0xa7, 0xf3, 0xd0),
                Color32::from_rgb(0x34, 0xc7, 0x7b),
                Color32::from_rgb(0x0d, 0x87, 0x7b),
            ],
            ordinal: Sequential {
                low: Color32::from_rgb(45, 49, 58),
                high: Color32::from_rgb(56, 189, 248),
            },
            identity: IdentityEnvelope {
                saturation: 0.85,
                lightness: 0.75,
            },
        }
    }

    /// Series `i`, **folding** past the end of the ramp into [`Self::other`].
    ///
    /// Folding, not wrapping. Wrapping was the first draft and it is the worse
    /// failure: it makes series 0 and series 5 the *same colour* while both
    /// still claim to be data, which is precisely the collision the ramp is
    /// capped at five to avoid. A folded band is honest — it says "several
    /// things, not broken out".
    pub fn nth(&self, i: usize) -> Color32 {
        self.categorical.get(i).copied().unwrap_or(self.other)
    }

    /// Value arriving. Named for the encoding, not the hue.
    pub fn inbound(&self) -> Color32 {
        self.flow.positive
    }

    /// Value leaving.
    pub fn outbound(&self) -> Color32 {
        self.flow.negative
    }

    /// The classification tint for `ring`, saturating at [`Self::unobserved`].
    ///
    /// Saturating rather than wrapping for the same reason [`Self::nth`] folds:
    /// past the last named class there is no further judgement to show, and
    /// recycling `classes[0]` would claim one.
    pub fn class(&self, ring: u8) -> Color32 {
        self.classes
            .get(ring as usize)
            .copied()
            .unwrap_or(self.unobserved)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Round-tripping must not drift, or a ramp regenerated each frame would
    /// shimmer.
    #[test]
    fn oklab_round_trips_within_a_bit() {
        for c in [
            Color32::from_rgb(0x39, 0x87, 0xe5),
            Color32::from_rgb(255, 215, 0),
            Color32::from_rgb(12, 13, 16),
            Color32::WHITE,
        ] {
            let back = from_oklab(oklab(c));
            for (a, b) in [(c.r(), back.r()), (c.g(), back.g()), (c.b(), back.b())] {
                assert!(a.abs_diff(b) <= 1, "{c:?} -> {back:?}");
            }
        }
    }

    #[test]
    fn a_ramp_ends_where_it_says_it_does() {
        let s = SeriesPalette::tokyo_night().ordinal;
        assert_eq!(s.at(0.0), s.low);
        assert_eq!(s.at(1.0), s.high);
        // Out of range clamps rather than extrapolating into nonsense.
        assert_eq!(s.at(-5.0), s.low);
        assert_eq!(s.at(5.0), s.high);
    }

    #[test]
    fn rank_one_is_the_bright_end() {
        let s = SeriesPalette::tokyo_night().ordinal;
        assert_eq!(s.by_rank(0, 100), s.high);
        assert_eq!(s.by_rank(100, 100), s.low);
        // No total means nothing is ranked — recede, don't claim first place.
        assert_eq!(s.by_rank(1, 0), s.low);
    }

    #[test]
    fn diverging_sits_on_its_neutral_at_zero() {
        let d = SeriesPalette::tokyo_night().flow;
        assert_eq!(d.at(0.0), d.neutral);
        assert_eq!(d.at(1.0), d.positive);
        assert_eq!(d.at(-1.0), d.negative);
    }

    #[test]
    fn steps_covers_both_ends() {
        let s = SeriesPalette::tokyo_night().ordinal;
        assert!(s.steps(0).is_empty());
        assert_eq!(s.steps(1), vec![s.high]);
        let five = s.steps(5);
        assert_eq!(five.len(), 5);
        assert_eq!(five[0], s.low);
        assert_eq!(five[4], s.high);
    }

    /// The same identity must keep its colour across frames and sessions —
    /// these get compared between screenshots.
    #[test]
    fn identity_colour_is_stable_and_in_gamut() {
        let e = SeriesPalette::tokyo_night().identity;
        assert_eq!(e.color(12345), e.color(12345));
        assert_ne!(e.color(0), e.color(24)); // a third of the wheel apart
    }
}
